package jp.mycomp.zzz.f10.common.entity;

import jp.mycomp.zzz.common.entity.BaseEntity;

public class MstCompany extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.num_of_employee
     *
     * @mbg.generated
     */
    private Integer numOfEmployee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.cid
     *
     * @return the value of mst_company.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.cid
     *
     * @param cid the value for mst_company.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.name
     *
     * @return the value of mst_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.name
     *
     * @param name the value for mst_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.addr
     *
     * @return the value of mst_company.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.addr
     *
     * @param addr the value for mst_company.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.num_of_employee
     *
     * @return the value of mst_company.num_of_employee
     *
     * @mbg.generated
     */
    public Integer getNumOfEmployee() {
        return numOfEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.num_of_employee
     *
     * @param numOfEmployee the value for mst_company.num_of_employee
     *
     * @mbg.generated
     */
    public void setNumOfEmployee(Integer numOfEmployee) {
        this.numOfEmployee = numOfEmployee;
    }
}