package jp.mycomp.zzz.f10.common.entity;

import jp.mycomp.zzz.common.entity.BaseEntity;

public class MstEmployee extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.eid
     *
     * @mbg.generated
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.name
     *
     * @mbg.generated
     */
    private byte[] name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.cid
     *
     * @return the value of mst_employee.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.cid
     *
     * @param cid the value for mst_employee.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.eid
     *
     * @return the value of mst_employee.eid
     *
     * @mbg.generated
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.eid
     *
     * @param eid the value for mst_employee.eid
     *
     * @mbg.generated
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.addr
     *
     * @return the value of mst_employee.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.addr
     *
     * @param addr the value for mst_employee.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.age
     *
     * @return the value of mst_employee.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.age
     *
     * @param age the value for mst_employee.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.note
     *
     * @return the value of mst_employee.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.note
     *
     * @param note the value for mst_employee.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.name
     *
     * @return the value of mst_employee.name
     *
     * @mbg.generated
     */
    public byte[] getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.name
     *
     * @param name the value for mst_employee.name
     *
     * @mbg.generated
     */
    public void setName(byte[] name) {
        this.name = name;
    }
}