package jp.mycomp.zzz.f10.common.mapper;

import java.util.List;
import jp.mycomp.zzz.f10.common.entity.MstCompany;
import jp.mycomp.zzz.f10.common.entity.MstCompanyExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MstCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    long countByExample(MstCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int deleteByExample(MstCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int insert(MstCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int insertSelective(MstCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    List<MstCompany> selectByExample(MstCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    MstCompany selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MstCompany record, @Param("example") MstCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MstCompany record, @Param("example") MstCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MstCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MstCompany record);
}